const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const base = process.env.TEST_URL || 'http://127.0.0.1:4173';
async function main(){
 console.log('Launching isolated test browser');
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
 const results=[];
 const context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'Asia/Tokyo',reducedMotion:'reduce'});
 const page=await context.newPage();
 page.setDefaultTimeout(15000);
 const errors=[];
 page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE ERROR',e.message);});
 // Third-party analytics/maps are not part of this UI regression test.
 await context.route('**/*',route=>{
  const u=new URL(route.request().url());
  if(u.origin===new URL(base).origin)return route.continue();
  return route.abort();
 });
 await page.goto(base+'/?month=2026-09',{waitUntil:'domcontentloaded'});
 console.log('Page loaded');
 await page.waitForSelector('.day-open');
 assert.equal(await page.locator('#splash').isVisible(),false);
 assert.equal(await page.locator('#calendarGrid .day').count(),35);
 assert.equal(await page.locator('.local-pages-banner').count(),1);
 assert.equal(await page.locator('.radio-dock img').count(),1);
 assert.equal(await page.locator('.language-picker-options a').count(),5);
 assert.equal(await page.locator('.listing-form').count(),1);
 assert(await page.evaluate(()=>document.querySelector('#garbage').compareDocumentPosition(document.querySelector('.seo-intro'))&Node.DOCUMENT_POSITION_FOLLOWING));
 assert(await page.evaluate(()=>document.querySelector('#akindo').compareDocumentPosition(document.querySelector('.local-pages-banner'))&Node.DOCUMENT_POSITION_FOLLOWING));
 results.push('Layout structure, reduced-motion opening, September dates: PASS');
 await page.screenshot({path:'/private/tmp/otaru-renewal-desktop.png',fullPage:false});
 await page.locator('#eventSearch').fill('小樽地域遺産');
 await page.waitForTimeout(200);
 assert.equal(await page.locator('#eventList .event-card').count(),1);
 await page.locator('#viewList').click();
 assert.equal(await page.locator('.calendar-grid-shell').isVisible(),false);
 await page.reload();
 assert.equal(await page.locator('#viewList').getAttribute('aria-pressed'),'true');
 await page.locator('#viewCalendar').click();
 await page.locator('#eventSearch').fill('zz-no-result-zz');
 await page.waitForTimeout(200);
 assert.equal(await page.locator('.empty-results').count(),1);
 await page.locator('#eventSearch').fill('');
 await page.waitForTimeout(200);
 await page.locator('[data-filter="child"]').click();
 assert.equal(await page.locator('#eventList .event-card:not(.category-child)').count(),0);
 assert.equal(await page.locator('#civicArchive').isVisible(),false);
 await page.locator('[data-filter="civic"]').click();
 assert.equal(await page.locator('#civicArchive').isVisible(),true);
 await page.locator('[data-filter="all"]').click();
 await page.locator('#eventSearch').fill('小樽地域遺産');
 await page.waitForTimeout(200);
 assert.equal(await page.locator('#eventList .event-card').count(),1);
 await page.locator('#eventSearch').fill('');
 results.push('Search, empty results, saved list mode, category filter: PASS');
 const event=page.locator('#calendarGrid .event-pill').first();
 await event.click();
 assert.equal(await page.locator('#modal').isVisible(),true);
 assert.equal(await page.locator('#modal .close').evaluate(el=>el===document.activeElement),true);
 assert.match(await page.locator('#modalCalendarLink').getAttribute('href'),/calendar.google.com/);
 assert.match(await page.locator('#mapExternalLink').getAttribute('href'),/google.com\/maps/);
 assert.equal(await page.locator('main').evaluate(el=>el.inert),true);
 await page.keyboard.press('Escape');
 assert.equal(await page.locator('#modal').isVisible(),false);
 assert.equal(await page.locator('main').evaluate(el=>el.inert),false);
 const day=page.locator('[data-date="2026-09-13"] .day-open');
 await day.focus();await page.keyboard.press('Enter');
 assert.equal(await page.locator('#modal').isVisible(),true);
 assert.equal(await page.locator('#modal .radio-inline img').count(),1);
 await page.keyboard.press('Escape');
 results.push('Keyboard day selection, modal focus/Escape, calendar/map links: PASS');
 await page.getByRole('button',{name:'次月',exact:true}).click();
 assert.match(await page.locator('#monthTitle').innerText(),/10/);
 await page.getByRole('button',{name:'前月',exact:true}).click();
 assert.match(await page.locator('#monthTitle').innerText(),/9/);
 for(const width of [320,390,768,1440]){
  await page.setViewportSize({width,height:900});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Horizontal overflow at '+width);
  await page.locator('#calendar').scrollIntoViewIfNeeded();
  await page.screenshot({path:'/private/tmp/otaru-renewal-'+width+'.png'});
 }
 results.push('Month navigation and widths 320/390/768/1440, no horizontal overflow: PASS');
 for(const [path,lang] of [['/en/','en'],['/zh-hant/','zh-Hant'],['/zh-hans/','zh-Hans'],['/ko/','ko']]){
  await page.setViewportSize({width:390,height:844});
  await page.goto(base+path+'?month=2026-09');
  assert.equal(await page.locator('html').getAttribute('lang'),lang);
  assert.equal(await page.locator('.language-picker-options [data-lang-link]').count(),5);
  await page.locator('.language-picker summary').click();
  assert.equal(await page.locator('.language-picker-options').isVisible(),true);
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),lang+' overflow');
  assert(await page.locator('#eventList .event-card').count()>0);
 }
 results.push('Four translated interfaces and searches: PASS');
 const nojs=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});
 const nojsPage=await nojs.newPage();await nojsPage.goto(base);
 assert(await nojsPage.locator('#eventList .event-card').count()>0);
 assert.equal(await nojsPage.locator('#splash').isVisible(),false);
 results.push('JavaScript disabled: main event content remains readable: PASS');
 const motion=await browser.newContext({viewport:{width:390,height:844}});
 const opening=await motion.newPage();
 await opening.clock.install({time:new Date('2026-09-06T00:00:00+09:00')});
 await opening.clock.pauseAt(new Date('2026-09-06T00:00:01+09:00'));
 await opening.goto(base+'/?opening=1',{waitUntil:'domcontentloaded'});
 await opening.waitForSelector('#splash:not([hidden])',{state:'visible'});
 await opening.screenshot({path:'/private/tmp/otaru-renewal-opening.png',animations:'disabled'});
 await opening.locator('#skipOpening').click();
 await opening.clock.runFor(300);
 await opening.waitForSelector('#splash[hidden]',{state:'hidden'});
 assert.equal(await opening.locator('main').evaluate(el=>el.inert),false);
 await opening.goto(base);
 assert.equal(await opening.locator('#splash').isVisible(),false);
 await opening.goto(base+'/?opening=1',{waitUntil:'domcontentloaded'});
 await opening.clock.runFor(1800);
 assert.equal(await opening.locator('#splash').isVisible(),false);
 await opening.screenshot({path:'/private/tmp/otaru-renewal-mobile-top.png'});
 results.push('Opening visible, skip, session repeat suppressed: PASS');
 assert.deepEqual(errors,[]);
 results.push('JavaScript runtime errors: 0');
 fs.writeFileSync('/private/tmp/otaru-renewal-test-results.json',JSON.stringify(results,null,2));
 console.log(results.join('\n'));
 await browser.close();
}
main().catch(e=>{console.error(e);process.exit(1);});
